---
apiVersion: v1
kind: Namespace
metadata:
  name: hellopage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellopage
  namespace: hellopage
  labels:
    app: hellopage
  annotations:
    # https://docs.fluxcd.io/en/stable/references/automated-image-update.html
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellopage
  template:
    metadata:
      labels:
        app: hellopage
    spec:
      containers:
      - name: app
        image: gcr.io/int128-1313/github.com/int128/hellopage:dev-f391fa0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hellopage
  namespace: hellopage
  labels:
    app: hellopage
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: hellopage
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hellopage
  namespace: hellopage
spec:
  rules:
  - host: hellopage-127-0-0-1.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: hellopage
          servicePort: http